// region License
/** This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 *  If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
**/
// endregion
package com.vankorno.vankornodb.set

import android.database.sqlite.SQLiteDatabase
import android.util.Log
import com.vankorno.vankornodb.api.CurrEntity
import com.vankorno.vankornodb.api.WhereDsl
import com.vankorno.vankornodb.api.toContentValues
import com.vankorno.vankornodb.core.data.DbConstants.DbTAG
import com.vankorno.vankornodb.dbManagement.data.NormalSchemaBundle

/**
 * Updates the row with the specified WhereDsl conditions in the given table with the values from [obj].
 * Converts the entity into ContentValues and performs the SQLite update operation.
 * If [schemaBundle] isn't passed or if it doesn't have a setter - reflection-based mapping is used.
 *
 * @param table The name of the table to update.
 * @param obj The entity object with updated data.
 * @param schemaBundle The bundle of an entity class, set/get functions, etc. (Generated by the IDE plugin)
 * @param where DSL conditions.
 * @return The number of rows affected.
 */
inline fun <T : CurrEntity> SQLiteDatabase.setObj(             table: String,
                                                                 obj: T,
                                                        schemaBundle: NormalSchemaBundle<T>? = null,
                                                               where: WhereDsl.()->Unit,
): Int {
    val cv = toContentValues(obj, schemaBundle)
    val whereDsl = WhereDsl().apply(where)
    val whereClause = whereDsl.clauses.joinToString(" ")
    val whereArgs = whereDsl.args.toTypedArray()
    
    val affected = update(table, cv, whereClause, whereArgs)
    if (affected > 1) {
        // region LOG
        Log.w(DbTAG, "setObj: $affected rows updated in '$table'. You may want to set more specific conditions if you want to update a single row.")
        // endregion
    }
    return affected
}






