package com.vankorno.sandbox._entities.testEntity.lite

import com.vankorno.vankornodb.api.EntityColumns
import com.vankorno.vankornodb.api.LiteEntity
import com.vankorno.vankornodb.dbManagement.data.LiteSchemaBundle
import com.vankorno.vankornodb.dbManagement.data.bCol
import com.vankorno.vankornodb.dbManagement.data.iCol
import com.vankorno.vankornodb.dbManagement.data.sCol
import com.vankorno.vankornodb.misc.getBoolean

data class TestLiteEntity(
                                    val id: Int = -1,
                                  val name: String = "",
                              val position: Int = 0,
                               val enabled: Boolean = false,
) : LiteEntity




// Boilerplate, auto-generated by the IDE plugin

object SbTestLite : LiteSchemaBundle<TestLiteEntity>(
    clazz = TestLiteEntity::class,
    
    columns = CTestLite,
    
    getter = { cursor ->
        var idx = 0
        
        TestLiteEntity(
            id = cursor.getInt(idx++),
            name = cursor.getString(idx++),
            position = cursor.getInt(idx++),
            enabled = cursor.getBoolean(idx++),
        )
    }
)



object CTestLite : EntityColumns {
    val Id = iCol("id", -1)
    val Name = sCol("name", "")
    val Position = iCol("position", 0)
    val Enabled = bCol("enabled", false)


    override val columns = buildColList {
        +Id
        +Name
        +Position
        +Enabled
    }
}
