// region License
/** This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 *  If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
**/
// endregion
package com.vankorno.vankornodb.api

import android.content.ContentValues
import android.database.Cursor
import com.vankorno.vankornodb.dbManagement.data.BaseEntity
import com.vankorno.vankornodb.dbManagement.data.BaseSchemaBundle
import com.vankorno.vankornodb.dbManagement.data.NormalEntity
import com.vankorno.vankornodb.dbManagement.data.NormalSchemaBundle
import com.vankorno.vankornodb.mappers.toCV
import com.vankorno.vankornodb.mappers.toEntt

/**
 * Maps the current row of the Cursor to an instance of the specified data class [T].
 * Uses a getter, generated by the IDE plugin. If it doesn't exist - defaults to reflection-based mapping.
 *
 * @return An instance of [T] constructed from the current row of the Cursor.
 */
fun <T : BaseEntity> Cursor.toEntity(schemaBundle: BaseSchemaBundle<T>): T = toEntt(schemaBundle)



/**
 * Converts the given entity into ContentValues for SQLite operations.
 * Uses the setter, generated by the IDE plugin.
 * If [schemaBundle] isn't passed or if it doesn't have a setter - reflection-based mapping is used.
 * 
 * @param obj The data object to convert.
 * @param schemaBundle The bundle of an entity class, set/get functions, etc. (Generated by the IDE plugin)
 * @return ContentValues representing the entity suitable for database insertion/update.
 */
fun <T : NormalEntity> toContentValues(                          obj: T,
                                                        schemaBundle: NormalSchemaBundle<T>? = null,
): ContentValues = toCV(obj, schemaBundle)




