package com.vankorno.sandbox._entities.testEntity

import com.vankorno.vankornodb.api.CurrEntity
import com.vankorno.vankornodb.api.EntityColumns
import com.vankorno.vankornodb.dbManagement.data.CurrSchemaBundle
import com.vankorno.vankornodb.dbManagement.data.bCol
import com.vankorno.vankornodb.dbManagement.data.fCol
import com.vankorno.vankornodb.dbManagement.data.iCol
import com.vankorno.vankornodb.dbManagement.data.lCol
import com.vankorno.vankornodb.dbManagement.data.sCol
import com.vankorno.vankornodb.misc.getBoolean

data class TestEntity(
                                    val id: Int = -1,
                                  val name: String = "",
                              val position: Int = 0,
                               val enabled: Boolean = false,
                                  val int1: Int = 0,
                                  val int2: Int = 0,
                                  val int3: Int = 0,
                                  val str1: String = "",
                                  val str2: String = "",
                                  val str3: String = "",
                                 val bool1: Boolean = false,
                                 val bool2: Boolean = false,
                                 val bool3: Boolean = false,
                                 val long1: Long = 0L,
                                 val long2: Long = 0L,
                                 val long3: Long = 0L,
                                val float1: Float = 0F,
                                val float2: Float = 0F,
                                val float3: Float = 0F,
) : CurrEntity




// Boilerplate, auto-generated by the IDE plugin





object _Test : CurrSchemaBundle<TestEntity>(
    clazz = TestEntity::class,

    columns = CTest,

    getter = { cursor ->
        var idx = 0

        TestEntity(
            id = cursor.getInt(idx++),
            name = cursor.getString(idx++),
            position = cursor.getInt(idx++),
            enabled = cursor.getBoolean(idx++),
            int1 = cursor.getInt(idx++),
            int2 = cursor.getInt(idx++),
            int3 = cursor.getInt(idx++),
            str1 = cursor.getString(idx++),
            str2 = cursor.getString(idx++),
            str3 = cursor.getString(idx++),
            bool1 = cursor.getBoolean(idx++),
            bool2 = cursor.getBoolean(idx++),
            bool3 = cursor.getBoolean(idx++),
            long1 = cursor.getLong(idx++),
            long2 = cursor.getLong(idx++),
            long3 = cursor.getLong(idx++),
            float1 = cursor.getFloat(idx++),
            float2 = cursor.getFloat(idx++),
            float3 = cursor.getFloat(idx++)
        )
    },

    setter = { e, cv ->
        cv.put("id", e.id)
        cv.put("name", e.name)
        cv.put("position", e.position)
        cv.put("enabled", e.enabled)
        cv.put("int1", e.int1)
        cv.put("int2", e.int2)
        cv.put("int3", e.int3)
        cv.put("str1", e.str1)
        cv.put("str2", e.str2)
        cv.put("str3", e.str3)
        cv.put("bool1", e.bool1)
        cv.put("bool2", e.bool2)
        cv.put("bool3", e.bool3)
        cv.put("long1", e.long1)
        cv.put("long2", e.long2)
        cv.put("long3", e.long3)
        cv.put("float1", e.float1)
        cv.put("float2", e.float2)
        cv.put("float3", e.float3)
        cv
    },
)





object CTest : EntityColumns {
    val Id = iCol("id", -1)
    val Name = sCol("name", "")
    val Position = iCol("position", 0)
    val Enabled = bCol("enabled", false)
    val Int1 = iCol("int1", 0)
    val Int2 = iCol("int2", 0)
    val Int3 = iCol("int3", 0)
    val Str1 = sCol("str1", "")
    val Str2 = sCol("str2", "")
    val Str3 = sCol("str3", "")
    val Bool1 = bCol("bool1", false)
    val Bool2 = bCol("bool2", false)
    val Bool3 = bCol("bool3", false)
    val Long1 = lCol("long1", 0L)
    val Long2 = lCol("long2", 0L)
    val Long3 = lCol("long3", 0L)
    val Float1 = fCol("float1", 0F)
    val Float2 = fCol("float2", 0F)
    val Float3 = fCol("float3", 0F)

    override val columns = buildColList {
        +Id
        +Name
        +Position
        +Enabled
        +Int1
        +Int2
        +Int3
        +Str1
        +Str2
        +Str3
        +Bool1
        +Bool2
        +Bool3
        +Long1
        +Long2
        +Long3
        +Float1
        +Float2
        +Float3
    }
}