package com.vankorno.sandbox.entities.testEntity

import com.vankorno.vankornodb.api.DbEntity
import com.vankorno.vankornodb.api.EntityColumns
import com.vankorno.vankornodb.dbManagement.data.bCol
import com.vankorno.vankornodb.dbManagement.data.fCol
import com.vankorno.vankornodb.dbManagement.data.iCol
import com.vankorno.vankornodb.dbManagement.data.lCol
import com.vankorno.vankornodb.dbManagement.data.sCol

data class TestEntity(
                                  val name: String = "",
                                   val boo: Boolean = false,
                                  val int1: Int = 0,
                                  val str1: String = "",
                                 val long1: Long = 0L,
                                val float1: Float = 0F,
                                    val id: Int = -1,
) : DbEntity




// Boilerplate, auto-generated by the IDE plugin

object TestCol : EntityColumns {
    val Name = sCol("name", "")
    val Boo = bCol("boo", false)
    val Int1 = iCol("int1", 0)
    val Str1 = sCol("str1", "")
    val Long1 = lCol("long1", 0L)
    val Float1 = fCol("float1", 0F)
    val Id = iCol("id", -1)


    override val columns = buildColList {
        +Name
        +Boo
        +Int1
        +Str1
        +Long1
        +Float1
        +Id
    }
}