package com.vankorno.sandbox.entities.testEntity

import com.vankorno.vankornodb.api.DbEntity
import com.vankorno.vankornodb.api.EntityColumns
import com.vankorno.vankornodb.dbManagement.data.bCol
import com.vankorno.vankornodb.dbManagement.data.fCol
import com.vankorno.vankornodb.dbManagement.data.iCol
import com.vankorno.vankornodb.dbManagement.data.lCol
import com.vankorno.vankornodb.dbManagement.data.sCol

data class TestEntity(
                                    val id: Int = -1,
                                  val name: String = "",
                              val position: Int = 0,
                               val enabled: Boolean = false,
                                  val int1: Int = 0,
                                  val int2: Int = 0,
                                  val int3: Int = 0,
                                  val str1: String = "",
                                  val str2: String = "",
                                  val str3: String = "",
                                 val bool1: Boolean = false,
                                 val bool2: Boolean = false,
                                 val bool3: Boolean = false,
                                 val long1: Long = 0L,
                                 val long2: Long = 0L,
                                 val long3: Long = 0L,
                                val float1: Float = 0F,
                                val float2: Float = 0F,
                                val float3: Float = 0F,
) : DbEntity




// Boilerplate, auto-generated by the IDE plugin

object CTest : EntityColumns {
    val Id = iCol("id", -1)
    val Name = sCol("name", "")
    val Position = iCol("position", 0)
    val Enabled = bCol("enabled", false)
    val Int1 = iCol("int1", 0)
    val Int2 = iCol("int2", 0)
    val Int3 = iCol("int3", 0)
    val Str1 = sCol("str1", "")
    val Str2 = sCol("str2", "")
    val Str3 = sCol("str3", "")
    val Bool1 = bCol("bool1", false)
    val Bool2 = bCol("bool2", false)
    val Bool3 = bCol("bool3", false)
    val Long1 = lCol("long1", 0L)
    val Long2 = lCol("long2", 0L)
    val Long3 = lCol("long3", 0L)
    val Float1 = fCol("float1", 0F)
    val Float2 = fCol("float2", 0F)
    val Float3 = fCol("float3", 0F)


    override val columns = buildColList {
        +Id
        +Name
        +Position
        +Enabled
        +Int1
        +Int2
        +Int3
        +Str1
        +Str2
        +Str3
        +Bool1
        +Bool2
        +Bool3
        +Long1
        +Long2
        +Long3
        +Float1
        +Float2
        +Float3
    }
}